const styles: Record<string, { bg: string; text: string; border: string }> = {
  new: { bg: 'bg-neutral-100', text: 'text-brand-text', border: 'border border-neutral-200' },
  contacted: { bg: 'bg-neutral-100', text: 'text-brand-text', border: 'border border-neutral-200' },
  audit_sent: { bg: 'bg-neutral-100', text: 'text-brand-text', border: 'border border-neutral-200' },
  proposal: { bg: 'bg-neutral-100', text: 'text-brand-text', border: 'border border-neutral-200' },
  won: { bg: 'bg-neutral-100', text: 'text-brand-text', border: 'border border-neutral-300' },
  lost: { bg: 'bg-red-50', text: 'text-brand-red', border: 'border border-red-100' },
  active: { bg: 'bg-neutral-100', text: 'text-brand-text', border: 'border border-neutral-300' },
  paused: { bg: 'bg-neutral-50', text: 'text-brand-muted', border: 'border border-neutral-200' },
  churned: { bg: 'bg-red-50', text: 'text-brand-red', border: 'border border-red-100' },
  submitted: { bg: 'bg-yellow-50', text: 'text-yellow-800', border: 'border border-yellow-200' },
  documents_pending: { bg: 'bg-orange-50', text: 'text-orange-800', border: 'border border-orange-200' },
  under_review: { bg: 'bg-blue-50', text: 'text-blue-800', border: 'border border-blue-200' },
  credit_analysis_complete: { bg: 'bg-indigo-50', text: 'text-indigo-800', border: 'border border-indigo-200' },
  funding_review: { bg: 'bg-purple-50', text: 'text-purple-800', border: 'border border-purple-200' },
  additional_information_requested: { bg: 'bg-amber-50', text: 'text-amber-800', border: 'border border-amber-200' },
  approved: { bg: 'bg-green-50', text: 'text-green-800', border: 'border border-green-200' },
  declined: { bg: 'bg-red-50', text: 'text-brand-red', border: 'border border-red-100' },
  denied: { bg: 'bg-red-50', text: 'text-brand-red', border: 'border border-red-100' },
  completed: { bg: 'bg-emerald-50', text: 'text-emerald-800', border: 'border border-emerald-200' },
  archived: { bg: 'bg-neutral-50', text: 'text-brand-muted', border: 'border border-neutral-200' },
  scheduled: { bg: 'bg-blue-50', text: 'text-blue-800', border: 'border border-blue-200' },
  cancelled: { bg: 'bg-red-50', text: 'text-brand-red', border: 'border border-red-100' },
  new_lead: { bg: 'bg-neutral-100', text: 'text-brand-text', border: 'border border-neutral-200' },
  consultation_scheduled: { bg: 'bg-blue-50', text: 'text-blue-800', border: 'border border-blue-200' },
  qualified: { bg: 'bg-indigo-50', text: 'text-indigo-800', border: 'border border-indigo-200' },
  converted: { bg: 'bg-green-50', text: 'text-green-800', border: 'border border-green-200' },
  not_interested: { bg: 'bg-neutral-50', text: 'text-brand-muted', border: 'border border-neutral-200' },
  intake_started: { bg: 'bg-yellow-50', text: 'text-yellow-800', border: 'border border-yellow-200' },
  intake_completed: { bg: 'bg-yellow-50', text: 'text-yellow-800', border: 'border border-yellow-200' },
  credit_analysis: { bg: 'bg-indigo-50', text: 'text-indigo-800', border: 'border border-indigo-200' },
  funding_analysis: { bg: 'bg-purple-50', text: 'text-purple-800', border: 'border border-purple-200' },
  recommendations_delivered: { bg: 'bg-green-50', text: 'text-green-800', border: 'border border-green-200' },
  active_client: { bg: 'bg-emerald-50', text: 'text-emerald-800', border: 'border border-emerald-200' },
}

const labels: Record<string, string> = {
  new: 'New',
  contacted: 'Contacted',
  audit_sent: 'Audit Sent',
  proposal: 'Proposal',
  won: 'Won',
  lost: 'Lost',
  active: 'Active',
  paused: 'Paused',
  churned: 'Churned',
  submitted: 'Submitted',
  documents_pending: 'Documents Pending',
  under_review: 'Under Review',
  credit_analysis_complete: 'Credit Analysis Complete',
  funding_review: 'Funding Review',
  additional_information_requested: 'Additional Info Requested',
  approved: 'Approved',
  declined: 'Declined',
  denied: 'Declined',
  completed: 'Completed',
  archived: 'Archived',
  scheduled: 'Scheduled',
  cancelled: 'Cancelled',
  new_lead: 'New Lead',
  consultation_scheduled: 'Consultation Scheduled',
  qualified: 'Qualified',
  converted: 'Converted',
  not_interested: 'Not Interested',
  intake_started: 'Intake Started',
  intake_completed: 'Intake Completed',
  credit_analysis: 'Credit Analysis',
  funding_analysis: 'Funding Analysis',
  recommendations_delivered: 'Recommendations Delivered',
  active_client: 'Active Client',
}

export default function StatusBadge({ status }: { status: string }) {
  const s = styles[status] || styles.new
  return (
    <span className={`inline-flex px-2.5 py-1 rounded-md text-[10px] font-bold tracking-[0.08em] uppercase ${s.bg} ${s.text} ${s.border}`}>
      {labels[status] || status}
    </span>
  )
}
